// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Conversation struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	PhoneNumber         string
	Jid                 sql.NullString
	Context             sql.NullString
	ConversationBuffer  sql.NullString
	ConversationSummary sql.NullString
	UserName            sql.NullString
}
