// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Agent struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description string
}

type Message struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.NullUUID
	Role      sql.NullString
	Content   sql.NullString
	ParentID  uuid.NullUUID
}

type User struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PhoneNumber string
	Jid         sql.NullString
	TelegramID  sql.NullString
	Context     sql.NullString
	UserName    sql.NullString
}
